[W 2024-06-05 13:45:36.174 ServerApp] jupyter_server_terminals | error adding extension (enabled: True): Jupyter Server Terminals requires Jupyter Server 2.0+
    Traceback (most recent call last):
      File "/home/users/pete_nut/miniconda3/envs/petes_env/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 320, in add_extension
        extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
      File "/home/users/pete_nut/miniconda3/envs/petes_env/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 166, in __init__
        super().__init__(*args, **kwargs)
      File "/home/users/pete_nut/miniconda3/envs/petes_env/lib/python3.8/site-packages/traitlets/traitlets.py", line 1371, in __init__
        value = self._traits[key]._cross_validate(self, getattr(self, key))
      File "/home/users/pete_nut/miniconda3/envs/petes_env/lib/python3.8/site-packages/traitlets/traitlets.py", line 732, in _cross_validate
        value = obj._trait_validators[self.name](obj, proposal)
      File "/home/users/pete_nut/miniconda3/envs/petes_env/lib/python3.8/site-packages/traitlets/traitlets.py", line 1243, in __call__
        return self.func(*args, **kwargs)
      File "/home/users/pete_nut/miniconda3/envs/petes_env/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 175, in _validate_name
        self._module, self._metadata = get_metadata(name)
      File "/home/users/pete_nut/miniconda3/envs/petes_env/lib/python3.8/site-packages/jupyter_server/extension/utils.py", line 60, in get_metadata
        module = importlib.import_module(package_name)
      File "/home/users/pete_nut/miniconda3/envs/petes_env/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 843, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/home/users/pete_nut/miniconda3/envs/petes_env/lib/python3.8/site-packages/jupyter_server_terminals/__init__.py", line 9, in <module>
        raise RuntimeError("Jupyter Server Terminals requires Jupyter Server 2.0+")
    RuntimeError: Jupyter Server Terminals requires Jupyter Server 2.0+
[I 2024-06-05 13:45:36.337 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-06-05 13:45:36.337 ServerApp] jupyter_resource_usage | extension was successfully linked.
[I 2024-06-05 13:45:36.342 ServerApp] jupyter_server_fileid | extension was successfully linked.
[I 2024-06-05 13:45:36.346 ServerApp] jupyter_server_ydoc | extension was successfully linked.
[I 2024-06-05 13:45:36.352 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-06-05 13:45:36.356 ServerApp] nbclassic | extension was successfully linked.
[I 2024-06-05 13:45:37.239 ServerApp] nbresuse | extension was found and enabled by notebook_shim. Consider moving the extension to Jupyter Server's extension paths.
[I 2024-06-05 13:45:37.239 ServerApp] nbresuse | extension was successfully linked.
[I 2024-06-05 13:45:37.239 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-06-05 13:45:37.323 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-06-05 13:45:37.325 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-06-05 13:45:37.326 ServerApp] jupyter_resource_usage | extension was successfully loaded.
[I 2024-06-05 13:45:37.326 FileIdExtension] Configured File ID manager: ArbitraryFileIdManager
[I 2024-06-05 13:45:37.327 FileIdExtension] ArbitraryFileIdManager : Configured root dir: /home/users/pete_nut/shipping_ccf
[I 2024-06-05 13:45:37.327 FileIdExtension] ArbitraryFileIdManager : Configured database path: /home/users/pete_nut/.local/share/jupyter/file_id_manager.db
[I 2024-06-05 13:45:37.329 FileIdExtension] ArbitraryFileIdManager : Successfully connected to database file.
[I 2024-06-05 13:45:37.329 FileIdExtension] ArbitraryFileIdManager : Creating File ID tables and indices with journal_mode = DELETE
[I 2024-06-05 13:45:37.336 ServerApp] jupyter_server_fileid | extension was successfully loaded.
[I 2024-06-05 13:45:37.337 ServerApp] jupyter_server_ydoc | extension was successfully loaded.
[I 2024-06-05 13:45:37.346 LabApp] JupyterLab extension loaded from /home/users/pete_nut/miniconda3/envs/petes_env/lib/python3.8/site-packages/jupyterlab
[I 2024-06-05 13:45:37.346 LabApp] JupyterLab application directory is /home/users/pete_nut/miniconda3/envs/petes_env/share/jupyter/lab
[I 2024-06-05 13:45:37.349 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-06-05 13:45:37.362 ServerApp] nbclassic | extension was successfully loaded.
[W 2024-06-05 13:45:37.362 ServerApp] nbresuse | extension failed loading with message: Duplicated timeseries in CollectorRegistry: {'total_memory_usage'}
[E 2024-06-05 13:45:37.362 ServerApp] nbresuse | stack trace
    Traceback (most recent call last):
      File "/home/users/pete_nut/miniconda3/envs/petes_env/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 355, in load_extension
        extension.load_all_points(self.serverapp)
      File "/home/users/pete_nut/miniconda3/envs/petes_env/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 229, in load_all_points
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
      File "/home/users/pete_nut/miniconda3/envs/petes_env/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 229, in <listcomp>
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
      File "/home/users/pete_nut/miniconda3/envs/petes_env/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 222, in load_point
        return point.load(serverapp)
      File "/home/users/pete_nut/miniconda3/envs/petes_env/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 148, in load
        return loader(serverapp)
      File "/home/users/pete_nut/miniconda3/envs/petes_env/lib/python3.8/site-packages/nbresuse/__init__.py", line 49, in load_jupyter_server_extension
        PrometheusHandler(PSUtilMetricsLoader(nbapp)), 1000
      File "/home/users/pete_nut/miniconda3/envs/petes_env/lib/python3.8/site-packages/nbresuse/prometheus.py", line 25, in __init__
        gauge = Gauge(phrase, "counter for " + phrase.replace("_", " "), [])
      File "/home/users/pete_nut/miniconda3/envs/petes_env/lib/python3.8/site-packages/prometheus_client/metrics.py", line 378, in __init__
        super().__init__(
      File "/home/users/pete_nut/miniconda3/envs/petes_env/lib/python3.8/site-packages/prometheus_client/metrics.py", line 155, in __init__
        registry.register(self)
      File "/home/users/pete_nut/miniconda3/envs/petes_env/lib/python3.8/site-packages/prometheus_client/registry.py", line 43, in register
        raise ValueError(
    ValueError: Duplicated timeseries in CollectorRegistry: {'total_memory_usage'}
[I 2024-06-05 13:45:37.368 ServerApp] Serving notebooks from local directory: /home/users/pete_nut/shipping_ccf
[I 2024-06-05 13:45:37.368 ServerApp] Jupyter Server 1.24.0 is running at:
[I 2024-06-05 13:45:37.368 ServerApp] http://localhost:8888/lab?token=20d807fd2491400da1be77342bfe418fb9cde5101331d1ac
[I 2024-06-05 13:45:37.368 ServerApp]  or http://127.0.0.1:8888/lab?token=20d807fd2491400da1be77342bfe418fb9cde5101331d1ac
[I 2024-06-05 13:45:37.368 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-06-05 13:45:37.380 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/users/pete_nut/.local/share/jupyter/runtime/jpserver-48880-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=20d807fd2491400da1be77342bfe418fb9cde5101331d1ac
     or http://127.0.0.1:8888/lab?token=20d807fd2491400da1be77342bfe418fb9cde5101331d1ac
[I 2024-06-05 13:45:37.426 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2024-06-05 14:03:07.228 ServerApp] 302 GET /?token=[secret] (127.0.0.1) 0.52ms
[W 2024-06-05 14:03:09.085 ServerApp] 404 GET /api/me?1717592588436 (127.0.0.1) 26.55ms referer=http://localhost:8888/lab
[W 2024-06-05 14:03:10.583 LabApp] Could not determine jupyterlab build status without nodejs
[I 2024-06-05 14:06:36.009 ServerApp] Creating new directory in 
[I 2024-06-05 14:07:19.125 ServerApp] Kernel started: 34c6bd69-8082-4544-88be-2a2f987f233e
[W 2024-06-05 14:07:20.305 ServerApp] Could not destroy zmq context for <jupyter_client.asynchronous.client.AsyncKernelClient object at 0x7fc30190a940>
[I 2024-06-05 14:08:21.010 ServerApp] Kernel shutdown: 34c6bd69-8082-4544-88be-2a2f987f233e
[W 2024-06-05 14:08:23.690 ServerApp] delete /preprocessing/collocate_ERA5.ipynb
[I 2024-06-05 14:12:57.955 ServerApp] Kernel started: 8c309bf5-1209-4b62-be17-5d40e31a8fbc
/home/users/pete_nut/miniconda3/envs/petes_env/lib/python3.8/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[W 2024-06-05 14:12:58.990 ServerApp] Could not destroy zmq context for <jupyter_client.asynchronous.client.AsyncKernelClient object at 0x7fc301b21700>
[I 2024-06-05 14:13:07.225 ServerApp] Creating new file in /preprocessing
[I 2024-06-05 14:13:32.244 ServerApp] Saving file at /preprocessing/subset_EIS.py
[I 2024-06-05 14:13:40.111 ServerApp] Kernel shutdown: 8c309bf5-1209-4b62-be17-5d40e31a8fbc
[W 2024-06-05 14:13:47.826 ServerApp] delete /preprocessing/subset_EIS.ipynb
2015
EIS_2015.nc
2016
EIS_2016.nc
[I 2024-06-05 14:25:08.888 ServerApp] Kernel started: bebc7203-01f9-4768-b72c-1b0f8e7f008f
[W 2024-06-05 14:25:09.947 ServerApp] Could not destroy zmq context for <jupyter_client.asynchronous.client.AsyncKernelClient object at 0x7fc301a6d190>
[I 2024-06-05 14:25:29.830 ServerApp] Saving file at /organise_regressors.ipynb
